
server:
  port: 9060
spring:
  application:
    name: order
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719   #机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互


security:
  oauth2:
    resource:
      jwt:
        key-uri:  http://auth.nb.com:9090/oauth/token_key  #获取解析jwt，验签名key的路径
    client:
      client-id:  orderService #获取验签key需要身份认证，这里是网关的clientId
      client-secret:  123456  #获取验签key需要身份认证，这里是网关的secret
