zuul:
  routes:
    token:
      url:  http://localhost:9090
    order:
      url:  http://localhost:9060
  sensitive-headers:  null   #\u654F\u611F\u5934\uFF0C\u8BF7\u6C42\u5934\u6709\u6B64\u5C5E\u6027 zuul\u4E0D\u5F80\u4E0B\u8F6C\u53D1,\u8BBE\u7F6E\u6210null\uFF0C\u6240\u6709\u8BF7\u6C42\u90FD\u8F6C\u53D1\uFF0Czuul\u9ED8\u8BA4\u6709Authorization\uFF0CCookie Set-Cookie
server:
  port: 9070



