zuul:
  routes: #路由的配置是个Map，可以配置多个
    token:  #token结尾的请求，都转发到http://localhost:9090认证服务器地址
      url:  http://localhost:9090
    order:  #order结尾的请求，都转发到http://localhost:9060 顶单服务
      url:  http://localhost:9060
  sensitive-headers:  null  #设置敏感头设置为空，Authorization等请求头的请求，都往后转发


server:
  port: 9070



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_oauth?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    password:
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: -1


#mybatis plus \u8BBE\u7F6E
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # \u5173\u95EDMP3.0\u81EA\u5E26\u7684banner
    banner: false
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E",1:"\u8BE5\u7C7B\u578B\u4E3A\u672A\u8BBE\u7F6E\u4E3B\u952E\u7C7B\u578B", 2:"\u7528\u6237\u8F93\u5165ID",3:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 4:"\u5168\u5C40\u552F\u4E00ID UUID",5:"\u5B57\u7B26\u4E32\u5168\u5C40\u552F\u4E00ID (idWorker \u7684\u5B57\u7B26\u4E32\u8868\u793A)";
      id-type: 0
      # \u9ED8\u8BA4\u6570\u636E\u5E93\u8868\u4E0B\u5212\u7EBF\u547D\u540D
      table-underline: true
  configuration:
    # \u8FD9\u4E2A\u914D\u7F6E\u4F1A\u5C06\u6267\u884C\u7684sql\u6253\u5370\u51FA\u6765\uFF0C\u5728\u5F00\u53D1\u6216\u6D4B\u8BD5\u7684\u65F6\u5019\u53EF\u4EE5\u7528
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



