
server:
  port: 9080

security:
  oauth2:
    resource:
      jwt:
        key-uri:  http://auth.nb.com:9090/oauth/token_key  #获取解析jwt，验签名key的路径
    client:
      client-id:  priceService #获取验签key需要身份认证，这里是网关的clientId
      client-secret:  123456  #获取验签key需要身份认证，这里是网关的secret